### ISSUE TITLE
More project info

### ISSUE THREAD

**Issue by LobAnovich** [Franticware/usb-to-ps1-mouse-pro#1]
Will description, BOM and diagrams be available?

**Comment by Franticware** [comment]
Please see the `kicad` subdirectory

**Comment by LobAnovich** [comment]
Are there plans to improve the circuit design of the board or is this the final version?

**Comment by Franticware** [comment]
I have had the PCBs made and completed building a few pieces of this adapter. They are working pretty well, so that would be a yes. I cannot rule out slight changes in the future though, especially the PCB layout.

**Comment by Franticware** [comment]
It is not.

**Comment by Franticware** [comment]
It is not. The USB-C is now reserved to programming and debugging purposes.

**Comment by Franticware** [comment]
It is not. The USB-C port is now reserved for programming and debugging purposes.

**Comment by Franticware** [comment]
https://github.com/Franticware/usb-to-ps1-mouse-pro/tree/main/wiring

**Comment by Franticware** [comment]
> Are there plans to improve the circuit design of the board or is this the final version?

There is now new revision PCB_3. Update to the wiring diagram will follow. It turns out previous versions of the board/wiring had issues with PSOne.
