### ISSUE TITLE
Two end pins. 

### ISSUE THREAD

**Issue by PSX-MAN** [Franticware/usb-to-ps1-mouse-pro#2]
Hello

Thank you for the awesome project and upgrade. I just have one question. These two pins are only connected to each other? Is it necessary to connect them?

![screen](https://github.com/user-attachments/assets/e653fd7e-1a80-4c5e-b484-8d28f95c715a)

Thank you

**Comment by Franticware** [comment]
![back](https://github.com/user-attachments/assets/f6b2c384-10da-49a4-9cd7-3bcad0b14757)
This is how it looks from the back. Also, the two pins tend to slide out as they are unsuported by the PCB. A drop of superglue might help. Not the best design, it will be resolved in the next PCB revision. There will also have to be a tweak to the 3D printed enclosure. I don't know when I get to fixing these issues, sorry.

**Comment by Franticware** [comment]
@PSX-MAN The kicad directory now contains an updated PCB revision that should clarify things. Additional documentation will follow eventually.

**Comment by PSX-MAN** [comment]
Great work, thank you very much.
